package Interfaz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafae
 */
public class MainFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAgregarResumen = new javax.swing.JPanel();
        lblTituloAgregar = new javax.swing.JLabel();
        lblRuta = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnSeleccionarArchivo = new javax.swing.JButton();
        btnAgregarResumen = new javax.swing.JButton();
        pnlAnalizarResumen = new javax.swing.JPanel();
        lblInstruccionAnalizar = new javax.swing.JLabel();
        scrListaInvestigaciones = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstInvestigaciones = new javax.swing.JList<>();
        btnAnalizar = new javax.swing.JButton();
        lblResultadosAnalisis = new javax.swing.JLabel();
        scrReporteAnalisis = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlBuscarPalabraClave = new javax.swing.JPanel();
        lblInstruccionPC = new javax.swing.JLabel();
        txtPalabraClave = new javax.swing.JTextField();
        btnBuscarPalabra = new javax.swing.JButton();
        lblResultadosPC = new javax.swing.JLabel();
        scrResultadosPalabra = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnVerDetallesPC = new javax.swing.JButton();
        pnlBuscarAutor = new javax.swing.JPanel();
        lblInstruccionAutor = new javax.swing.JLabel();
        cmbAutores = new javax.swing.JComboBox<>();
        btnVerDetallesAutor = new javax.swing.JButton();
        pnlListarPalabras = new javax.swing.JPanel();
        lblInstruccionListaPC = new javax.swing.JLabel();
        scrListaPalabrasClave = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btnVerDetallesPCLista = new javax.swing.JButton();
        lblDetallesPCLista = new javax.swing.JLabel();
        scrDetallesPalabraClave = new javax.swing.JScrollPane();
        txtDetallesPalabraClave = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloAgregar.setText("Carga de Archivo de Resumen Científico");

        lblRuta.setText("Ruta del Archivo (.txt):");

        jTextField2.setEditable(false);

        btnSeleccionarArchivo.setText("Buscar Archivo...");
        btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArchivoActionPerformed(evt);
            }
        });

        btnAgregarResumen.setText("AGREGAR RESUMEN");
        btnAgregarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarResumenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarResumenLayout = new javax.swing.GroupLayout(pnlAgregarResumen);
        pnlAgregarResumen.setLayout(pnlAgregarResumenLayout);
        pnlAgregarResumenLayout.setHorizontalGroup(
            pnlAgregarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                .addGroup(pnlAgregarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblTituloAgregar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblRuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAgregarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                                .addComponent(btnAgregarResumen)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                                .addComponent(btnSeleccionarArchivo)
                                .addGap(104, 104, 104)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlAgregarResumenLayout.setVerticalGroup(
            pnlAgregarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAgregarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuta)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarResumen)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1. Agregar Resumen", pnlAgregarResumen);

        lblInstruccionAnalizar.setText("Seleccione la Investigación a Analizar:");

        lstInvestigaciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstInvestigaciones);

        scrListaInvestigaciones.setViewportView(jScrollPane1);

        btnAnalizar.setText("Analizar Seleccion");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        lblResultadosAnalisis.setText("Estadísticas de Frecuencia de Palabras Clave:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        scrReporteAnalisis.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnlAnalizarResumenLayout = new javax.swing.GroupLayout(pnlAnalizarResumen);
        pnlAnalizarResumen.setLayout(pnlAnalizarResumenLayout);
        pnlAnalizarResumenLayout.setHorizontalGroup(
            pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                .addGroup(pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                        .addGroup(pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scrListaInvestigaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lblInstruccionAnalizar)))
                        .addGroup(pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lblResultadosAnalisis))
                            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(scrReporteAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlAnalizarResumenLayout.setVerticalGroup(
            pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruccionAnalizar)
                    .addComponent(lblResultadosAnalisis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrReporteAnalisis)
                    .addComponent(scrListaInvestigaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2. Analizar Resumen", pnlAnalizarResumen);

        lblInstruccionPC.setText("Ingrese la Palabra Clave a Buscar:");

        btnBuscarPalabra.setText("BUSCAR");

        lblResultadosPC.setText("Investigaciones Relacionadas:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrResultadosPalabra.setViewportView(jList1);

        btnVerDetallesPC.setText("VER DETALLES");

        javax.swing.GroupLayout pnlBuscarPalabraClaveLayout = new javax.swing.GroupLayout(pnlBuscarPalabraClave);
        pnlBuscarPalabraClave.setLayout(pnlBuscarPalabraClaveLayout);
        pnlBuscarPalabraClaveLayout.setHorizontalGroup(
            pnlBuscarPalabraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarPalabraClaveLayout.createSequentialGroup()
                .addGroup(pnlBuscarPalabraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarPalabraClaveLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblInstruccionPC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPalabraClave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPalabra))
                    .addGroup(pnlBuscarPalabraClaveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrResultadosPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarPalabraClaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlBuscarPalabraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarPalabraClaveLayout.createSequentialGroup()
                        .addComponent(btnVerDetallesPC)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarPalabraClaveLayout.createSequentialGroup()
                        .addComponent(lblResultadosPC)
                        .addGap(245, 245, 245))))
        );
        pnlBuscarPalabraClaveLayout.setVerticalGroup(
            pnlBuscarPalabraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarPalabraClaveLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlBuscarPalabraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruccionPC)
                    .addComponent(txtPalabraClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPalabra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultadosPC)
                .addGap(8, 8, 8)
                .addComponent(scrResultadosPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerDetallesPC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("3. Buscar por Palabra Clave", pnlBuscarPalabraClave);

        lblInstruccionAutor.setText("Seleccione el Autor para Buscar Investigaciones:");

        cmbAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnVerDetallesAutor.setText("BUSCAR INVESTIGACIONES");

        javax.swing.GroupLayout pnlBuscarAutorLayout = new javax.swing.GroupLayout(pnlBuscarAutor);
        pnlBuscarAutor.setLayout(pnlBuscarAutorLayout);
        pnlBuscarAutorLayout.setHorizontalGroup(
            pnlBuscarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarAutorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblInstruccionAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAutores, 0, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerDetallesAutor)
                .addGap(29, 29, 29))
        );
        pnlBuscarAutorLayout.setVerticalGroup(
            pnlBuscarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarAutorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlBuscarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruccionAutor)
                    .addComponent(cmbAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerDetallesAutor))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("4. Buscar por Autor", pnlBuscarAutor);

        lblInstruccionListaPC.setText("Palabras Clave Registradas (Orden Alfabético - AVL):");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrListaPalabrasClave.setViewportView(jList2);

        btnVerDetallesPCLista.setText("VER DETALLES");

        lblDetallesPCLista.setText("Detalles (Frecuencia y Artículos):");

        txtDetallesPalabraClave.setEditable(false);
        txtDetallesPalabraClave.setColumns(20);
        txtDetallesPalabraClave.setRows(5);
        scrDetallesPalabraClave.setViewportView(txtDetallesPalabraClave);

        javax.swing.GroupLayout pnlListarPalabrasLayout = new javax.swing.GroupLayout(pnlListarPalabras);
        pnlListarPalabras.setLayout(pnlListarPalabrasLayout);
        pnlListarPalabrasLayout.setHorizontalGroup(
            pnlListarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(pnlListarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnVerDetallesPCLista))
                    .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                        .addComponent(scrListaPalabrasClave, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(scrDetallesPalabraClave, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                        .addComponent(lblInstruccionListaPC)
                        .addGap(59, 59, 59)
                        .addComponent(lblDetallesPCLista)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlListarPalabrasLayout.setVerticalGroup(
            pnlListarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlListarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                        .addComponent(lblInstruccionListaPC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrListaPalabrasClave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                        .addComponent(lblDetallesPCLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrDetallesPalabraClave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerDetallesPCLista)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("5. Listar Palabras Clave", pnlListarPalabras);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("SuperMetroMendeley: Administrador de Artículos Científicos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

    private void btnAgregarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarResumenActionPerformed
        // TODO add your handling code here:String rutaArchivo = txtRutaArchivo.getText();
    
    // 1. VALIDACIÓN DE CAMPO VACÍO (Ruta)
    if (rutaArchivo == null || rutaArchivo.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "⚠️ Debe seleccionar un archivo de resumen antes de agregar.", 
            "Error de Validación", 
            JOptionPane.WARNING_MESSAGE);
        lblEstadoSistema.setText("❌ Inserción fallida: No se seleccionó archivo.");
        return; // Detiene la ejecución
    }

    // Convertir la ruta a un objeto File
    File archivo = new File(rutaArchivo);
    
    // 2. VALIDACIÓN DE EXISTENCIA DEL ARCHIVO
    if (!archivo.exists() || archivo.isDirectory()) {
        JOptionPane.showMessageDialog(this, 
            "⚠️ Error: El archivo especificado no existe o es una carpeta.", 
            "Error de Archivo", 
            JOptionPane.ERROR_MESSAGE);
        lblEstadoSistema.setText("❌ Inserción fallida: Archivo no encontrado.");
        return;
    }
    
   
    iniciarProcesamientoResumen(archivo);
    
    
    }//GEN-LAST:event_btnAgregarResumenActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalizarActionPerformed
// Crea este método en cualquier parte de tu clase MainFrame, pero fuera de cualquier otro método.
private void iniciarProcesamientoResumen(File archivo ) {
    
    try {

        // 1. Lectura del archivo para extraer Título y Palabras Clave.
        // 2. Generación de la Función Hash y BÚSQUEDA en la Hash Table para duplicados (O(1)).
        // 3. INSERCIÓN en: Hash Table, AVL Autores, AVL Palabras Clave (O(log n)).

        // FEEDBACK DE ÉXITO
        lblEstadoSistema.setText("✅ ¡Resumen agregado y estructuras actualizadas exitosamente!");
        txtRutaArchivo.setText(""); // Limpia la ruta
        
    } catch (Exception e) {
        lblEstadoSistema.setText("❌ Error al procesar o insertar datos: " + e.getMessage());
        txtRutaArchivo.setText(""); 
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarResumen;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnBuscarPalabra;
    private javax.swing.JButton btnSeleccionarArchivo;
    private javax.swing.JButton btnVerDetallesAutor;
    private javax.swing.JButton btnVerDetallesPC;
    private javax.swing.JButton btnVerDetallesPCLista;
    private javax.swing.JComboBox<String> cmbAutores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblDetallesPCLista;
    private javax.swing.JLabel lblInstruccionAnalizar;
    private javax.swing.JLabel lblInstruccionAutor;
    private javax.swing.JLabel lblInstruccionListaPC;
    private javax.swing.JLabel lblInstruccionPC;
    private javax.swing.JLabel lblResultadosAnalisis;
    private javax.swing.JLabel lblResultadosPC;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblTituloAgregar;
    private javax.swing.JList<String> lstInvestigaciones;
    private javax.swing.JPanel pnlAgregarResumen;
    private javax.swing.JPanel pnlAnalizarResumen;
    private javax.swing.JPanel pnlBuscarAutor;
    private javax.swing.JPanel pnlBuscarPalabraClave;
    private javax.swing.JPanel pnlListarPalabras;
    private javax.swing.JScrollPane scrDetallesPalabraClave;
    private javax.swing.JScrollPane scrListaInvestigaciones;
    private javax.swing.JScrollPane scrListaPalabrasClave;
    private javax.swing.JScrollPane scrReporteAnalisis;
    private javax.swing.JScrollPane scrResultadosPalabra;
    private javax.swing.JTextArea txtDetallesPalabraClave;
    private javax.swing.JTextField txtPalabraClave;
    // End of variables declaration//GEN-END:variables
}
