package Interfaz;

import logica.Controlador; 
import java.io.File;       
import javax.swing.JFileChooser; 
import javax.swing.JOptionPane;  

   
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafae
 */
public class MainFrame extends javax.swing.JFrame {

    private final Controlador controlador; 

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        lblTituloAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloAgregar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        this.controlador = new Controlador();
        this.setSize(950, 450);
        this.setLocationRelativeTo(null); // Para centrar la ventana
        actualizarListaResumenes();
        actualizarComboAutores();
        actualizarListaPalabrasClave();
        decorarInterfaz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAgregarResumen = new javax.swing.JPanel();
        lblTituloAgregar = new javax.swing.JLabel();
        lblRuta = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnSeleccionarArchivo = new javax.swing.JButton();
        btnAgregarResumen = new javax.swing.JButton();
        pnlAnalizarResumen = new javax.swing.JPanel();
        lblInstruccionAnalizar = new javax.swing.JLabel();
        scrListaInvestigaciones = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstInvestigaciones = new javax.swing.JList<>();
        btnAnalizar = new javax.swing.JButton();
        lblResultadosAnalisis = new javax.swing.JLabel();
        scrReporteAnalisis = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlBuscarPalabraClave = new javax.swing.JPanel();
        lblInstruccionPC = new javax.swing.JLabel();
        txtPalabraClave = new javax.swing.JTextField();
        btnBuscarPalabra = new javax.swing.JButton();
        lblResultadosPC = new javax.swing.JLabel();
        scrResultadosPalabra = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnVerDetallesPC = new javax.swing.JButton();
        pnlBuscarAutor = new javax.swing.JPanel();
        lblInstruccionAutor = new javax.swing.JLabel();
        cmbAutores = new javax.swing.JComboBox<>();
        btnVerDetallesAutor = new javax.swing.JButton();
        pnlListarPalabras = new javax.swing.JPanel();
        lblInstruccionListaPC = new javax.swing.JLabel();
        scrListaPalabrasClave = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        btnVerDetallesPCLista = new javax.swing.JButton();
        lblDetallesPCLista = new javax.swing.JLabel();
        scrDetallesPalabraClave = new javax.swing.JScrollPane();
        txtDetallesPalabraClave = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloAgregar.setText("Carga de Archivo de Resumen Científico");

        lblRuta.setText("Ruta del Archivo (.txt):");

        jTextField2.setEditable(false);

        btnSeleccionarArchivo.setText("Buscar Archivo...");
        btnSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArchivoActionPerformed(evt);
            }
        });

        btnAgregarResumen.setText("AGREGAR RESUMEN");
        btnAgregarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarResumenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarResumenLayout = new javax.swing.GroupLayout(pnlAgregarResumen);
        pnlAgregarResumen.setLayout(pnlAgregarResumenLayout);
        pnlAgregarResumenLayout.setHorizontalGroup(
            pnlAgregarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                .addGroup(pnlAgregarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblTituloAgregar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblRuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAgregarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                                .addComponent(btnAgregarResumen)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                                .addComponent(btnSeleccionarArchivo)
                                .addGap(104, 104, 104)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlAgregarResumenLayout.setVerticalGroup(
            pnlAgregarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAgregarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuta)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarResumen)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1. Agregar Resumen", pnlAgregarResumen);

        lblInstruccionAnalizar.setText("Seleccione la Investigación a Analizar:");

        lstInvestigaciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstInvestigaciones);

        scrListaInvestigaciones.setViewportView(jScrollPane1);

        btnAnalizar.setText("Analizar Seleccion");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        lblResultadosAnalisis.setText("Estadísticas de Frecuencia de Palabras Clave:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        scrReporteAnalisis.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnlAnalizarResumenLayout = new javax.swing.GroupLayout(pnlAnalizarResumen);
        pnlAnalizarResumen.setLayout(pnlAnalizarResumenLayout);
        pnlAnalizarResumenLayout.setHorizontalGroup(
            pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                .addGroup(pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                        .addGroup(pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scrListaInvestigaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lblInstruccionAnalizar)))
                        .addGroup(pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lblResultadosAnalisis))
                            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(scrReporteAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        pnlAnalizarResumenLayout.setVerticalGroup(
            pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnalizarResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruccionAnalizar)
                    .addComponent(lblResultadosAnalisis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAnalizarResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrReporteAnalisis)
                    .addComponent(scrListaInvestigaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2. Analizar Resumen", pnlAnalizarResumen);

        lblInstruccionPC.setText("Ingrese la Palabra Clave a Buscar:");

        btnBuscarPalabra.setText("BUSCAR");
        btnBuscarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPalabraActionPerformed(evt);
            }
        });

        lblResultadosPC.setText("Investigaciones Relacionadas:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrResultadosPalabra.setViewportView(jList1);

        btnVerDetallesPC.setText("VER DETALLES");
        btnVerDetallesPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesPCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarPalabraClaveLayout = new javax.swing.GroupLayout(pnlBuscarPalabraClave);
        pnlBuscarPalabraClave.setLayout(pnlBuscarPalabraClaveLayout);
        pnlBuscarPalabraClaveLayout.setHorizontalGroup(
            pnlBuscarPalabraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarPalabraClaveLayout.createSequentialGroup()
                .addGroup(pnlBuscarPalabraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarPalabraClaveLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblInstruccionPC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPalabraClave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPalabra))
                    .addGroup(pnlBuscarPalabraClaveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrResultadosPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarPalabraClaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlBuscarPalabraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarPalabraClaveLayout.createSequentialGroup()
                        .addComponent(btnVerDetallesPC)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarPalabraClaveLayout.createSequentialGroup()
                        .addComponent(lblResultadosPC)
                        .addGap(245, 245, 245))))
        );
        pnlBuscarPalabraClaveLayout.setVerticalGroup(
            pnlBuscarPalabraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarPalabraClaveLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pnlBuscarPalabraClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruccionPC)
                    .addComponent(txtPalabraClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPalabra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultadosPC)
                .addGap(8, 8, 8)
                .addComponent(scrResultadosPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerDetallesPC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("3. Buscar por Palabra Clave", pnlBuscarPalabraClave);

        lblInstruccionAutor.setText("Seleccione el Autor para Buscar Investigaciones:");

        cmbAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAutoresActionPerformed(evt);
            }
        });

        btnVerDetallesAutor.setText("BUSCAR INVESTIGACIONES");
        btnVerDetallesAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarAutorLayout = new javax.swing.GroupLayout(pnlBuscarAutor);
        pnlBuscarAutor.setLayout(pnlBuscarAutorLayout);
        pnlBuscarAutorLayout.setHorizontalGroup(
            pnlBuscarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarAutorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblInstruccionAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAutores, 0, 383, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerDetallesAutor)
                .addGap(29, 29, 29))
        );
        pnlBuscarAutorLayout.setVerticalGroup(
            pnlBuscarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarAutorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlBuscarAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInstruccionAutor)
                    .addComponent(cmbAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerDetallesAutor))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("4. Buscar por Autor", pnlBuscarAutor);

        lblInstruccionListaPC.setText("Palabras Clave Registradas (Orden Alfabético - AVL):");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrListaPalabrasClave.setViewportView(jList2);

        btnVerDetallesPCLista.setText("VER DETALLES");
        btnVerDetallesPCLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesPCListaActionPerformed(evt);
            }
        });

        lblDetallesPCLista.setText("Detalles (Frecuencia y Artículos):");

        txtDetallesPalabraClave.setEditable(false);
        txtDetallesPalabraClave.setColumns(20);
        txtDetallesPalabraClave.setRows(5);
        scrDetallesPalabraClave.setViewportView(txtDetallesPalabraClave);

        javax.swing.GroupLayout pnlListarPalabrasLayout = new javax.swing.GroupLayout(pnlListarPalabras);
        pnlListarPalabras.setLayout(pnlListarPalabrasLayout);
        pnlListarPalabrasLayout.setHorizontalGroup(
            pnlListarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(pnlListarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnVerDetallesPCLista))
                    .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                        .addComponent(scrListaPalabrasClave, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(scrDetallesPalabraClave, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                        .addComponent(lblInstruccionListaPC)
                        .addGap(59, 59, 59)
                        .addComponent(lblDetallesPCLista)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        pnlListarPalabrasLayout.setVerticalGroup(
            pnlListarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlListarPalabrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                        .addComponent(lblInstruccionListaPC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrListaPalabrasClave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlListarPalabrasLayout.createSequentialGroup()
                        .addComponent(lblDetallesPCLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrDetallesPalabraClave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerDetallesPCLista)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("5. Listar Palabras Clave", pnlListarPalabras);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("SuperMetroMendeley: Administrador de Artículos Científicos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArchivoActionPerformed
        JFileChooser selector = new JFileChooser();
        int resultado = selector.showOpenDialog(this);
        
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = selector.getSelectedFile();
            jTextField2.setText(archivo.getAbsolutePath()); 
        }
    }//GEN-LAST:event_btnSeleccionarArchivoActionPerformed

    private void btnAgregarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarResumenActionPerformed
        // 1. Obtener ruta de caja de texto 
        String ruta = jTextField2.getText(); 
        
        // 2. Validaciones
        if (ruta == null || ruta.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero seleccione un archivo.");
            return;
        }
        
        File archivo = new File(ruta);
        if (!archivo.exists()) {
            JOptionPane.showMessageDialog(this, "El archivo no existe.");
            return;
        }
        
        // 3. LLAMAR AL CONTROLADOR
        try {
            String mensaje = controlador.agregarResumen(archivo);
            JOptionPane.showMessageDialog(this, mensaje);
            
            if (mensaje.startsWith("¡Éxito")) {
                jTextField2.setText(""); // Limpiar campo
                actualizarListaResumenes();
                actualizarComboAutores();
                actualizarListaPalabrasClave();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error crítico: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarResumenActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // 1. Obtener qué título seleccionó el usuario en la lista
        String tituloSeleccionado = lstInvestigaciones.getSelectedValue();
        
        if (tituloSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una investigación de la lista primero.");
            return;
        }
        
        // 2. Buscar el objeto Resumen completo usando el controlador
        modelo.Resumen resumen = controlador.buscarResumenPorTitulo(tituloSeleccionado);
        
        if (resumen != null) {
            // 3. Generar el análisis (conteo de palabras)
            String reporte = controlador.analizarResumen(resumen);
            
            // 4. Mostrarlo en el área de texto (jTextArea1)
            jTextArea1.setText(reporte);
            // Hacer que el scroll suba al principio del texto
            jTextArea1.setCaretPosition(0); 
        }
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void cmbAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAutoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAutoresActionPerformed

    private void btnVerDetallesAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesAutorActionPerformed
        String autorSeleccionado = (String) cmbAutores.getSelectedItem();
        
        if (autorSeleccionado == null) return;
        
        // 1. Buscar en el Árbol AVL de Autores
        estructuras.ListaEnlazada<modelo.Resumen> resultados = controlador.buscarPorAutor(autorSeleccionado);
        
        // 2. Mostrar resultados en un Pop-up o lista
        // Como tu diseño no tiene una JList en esta pestaña (solo veo el combo y el botón),
        // mostraremos los títulos en un mensaje emergente por ahora.
        
        StringBuilder sb = new StringBuilder();
        sb.append("Investigaciones de ").append(autorSeleccionado).append(":\n\n");
        
        if (resultados != null && !resultados.estaVacia()) {
            for (modelo.Resumen r : resultados) {
                sb.append("- ").append(r.getTitulo()).append("\n");
            }
        } else {
            sb.append("Ninguna encontrada (Esto no debería pasar si está en el combo).");
        }
        
        JOptionPane.showMessageDialog(this, sb.toString());
    }//GEN-LAST:event_btnVerDetallesAutorActionPerformed

    private void btnBuscarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPalabraActionPerformed
        String palabra = txtPalabraClave.getText().trim();
        
        if (palabra.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escriba una palabra clave.");
            return;
        }
        
        // 1. Buscar en el Árbol AVL
        estructuras.ListaEnlazada<modelo.Resumen> resultados = controlador.buscarPorPalabraClave(palabra);
        
        // 2. Llenar la lista visual 
        javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();
        
        if (resultados != null && !resultados.estaVacia()) {
            for (modelo.Resumen r : resultados) {
                modelo.addElement(r.getTitulo());
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron investigaciones con esa palabra.");
        }
        
        jList1.setModel(modelo);
    }//GEN-LAST:event_btnBuscarPalabraActionPerformed

    private void btnVerDetallesPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesPCActionPerformed
        String titulo = jList1.getSelectedValue();
        
        if (titulo == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un resumen de la lista.");
            return;
        }
        
        modelo.Resumen r = controlador.buscarResumenPorTitulo(titulo);
        if (r != null) {
            JOptionPane.showMessageDialog(this, r.toString(), "Detalles del Resumen", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnVerDetallesPCActionPerformed

    private void btnVerDetallesPCListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesPCListaActionPerformed
       String palabraSeleccionada = jList2.getSelectedValue();
        
        if (palabraSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una palabra de la lista.");
            return;
        }
        
        // Buscamos los artículos donde aparece esa palabra
        estructuras.ListaEnlazada<modelo.Resumen> resultados = controlador.buscarPorPalabraClave(palabraSeleccionada);
        
        StringBuilder sb = new StringBuilder();
        sb.append("Artículos con la palabra clave '").append(palabraSeleccionada).append("':\n\n");
        
        if (resultados != null && !resultados.estaVacia()) {
            for (modelo.Resumen r : resultados) {
                // Calculamos cuántas veces aparece la palabra en ese resumen
                int frecuencia = controlador.analizarResumen(r).split(palabraSeleccionada).length - 1; 
                // Nota: El cálculo de frecuencia exacto ya lo hace tu Analizador, 
                // aquí solo mostramos el título para cumplir el requisito.
                sb.append("• ").append(r.getTitulo()).append("\n");
            }
        }
        
        txtDetallesPalabraClave.setText(sb.toString());
    }//GEN-LAST:event_btnVerDetallesPCListaActionPerformed

    // Método para refrescar la lista visual de investigaciones
    private void actualizarListaResumenes() {
        javax.swing.DefaultListModel<String> modeloLista = new javax.swing.DefaultListModel<>();
        
        // 1. Pedir al controlador la lista de todos los títulos
        // (Asegúrate de que tu Controlador tenga el método obtenerTodosLosTitulos)
        estructuras.ListaEnlazada<String> listaTitulos = controlador.obtenerTodosLosTitulos();
        
        // 2. Recorrer la lista enlazada y agregar al modelo visual
        for (String titulo : listaTitulos) {
            modeloLista.addElement(titulo);
        }
        
        // 3. Asignar el modelo a la JList (lstInvestigaciones)
        lstInvestigaciones.setModel(modeloLista);
    }
    
    private void actualizarComboAutores() {
        cmbAutores.removeAllItems();
        java.util.List<String> autores = controlador.obtenerAutoresRegistrados();
        
        if (autores != null) {
            for (String autor : autores) {
                cmbAutores.addItem(autor);
            }
        }
    }
    
    private void actualizarListaPalabrasClave() {
        javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();
        java.util.List<String> palabras = controlador.obtenerPalabrasClaveListadas();
        
        if (palabras != null) {
            for (String p : palabras) {
                modelo.addElement(p);
            }
        }
        // Asignamos a la lista de la pestaña 5 
        jList2.setModel(modelo);
    }
    
    private void decorarInterfaz() {
        // COLORES MODERNOS
        java.awt.Color colorFondo = java.awt.Color.WHITE;
        java.awt.Color colorPrimario = new java.awt.Color(0, 102, 204); // Azul profesional
        java.awt.Color colorTextoBtn = java.awt.Color.WHITE;
        java.awt.Font fuenteBotones = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14);

        // 1. PINTAR PANELES (Para quitar el gris triste)
        this.getContentPane().setBackground(colorFondo);
        pnlAgregarResumen.setBackground(colorFondo);
        pnlAnalizarResumen.setBackground(colorFondo);
        pnlBuscarAutor.setBackground(colorFondo);
        pnlBuscarPalabraClave.setBackground(colorFondo);
        pnlListarPalabras.setBackground(colorFondo);
        jTabbedPane1.setBackground(colorFondo);

        // 2. ESTILIZAR BOTONES (Función auxiliar para no repetir código)
        estilizarBoton(btnSeleccionarArchivo, colorPrimario, colorTextoBtn, fuenteBotones);
        estilizarBoton(btnAgregarResumen, new java.awt.Color(40, 167, 69), colorTextoBtn, fuenteBotones); // Verde para agregar
        estilizarBoton(btnAnalizar, colorPrimario, colorTextoBtn, fuenteBotones);
        estilizarBoton(btnBuscarPalabra, colorPrimario, colorTextoBtn, fuenteBotones);
        estilizarBoton(btnVerDetallesPC, colorPrimario, colorTextoBtn, fuenteBotones);
        estilizarBoton(btnVerDetallesAutor, colorPrimario, colorTextoBtn, fuenteBotones);
        estilizarBoton(btnVerDetallesPCLista, colorPrimario, colorTextoBtn, fuenteBotones);
    }

    // Método pequeño para aplicar estilo a cualquier botón
    private void estilizarBoton(javax.swing.JButton btn, java.awt.Color fondo, java.awt.Color texto, java.awt.Font fuente) {
        btn.setBackground(fondo);
        btn.setForeground(texto);
        btn.setFont(fuente);
        btn.setFocusPainted(false); // Quita el recuadro feo al hacer clic
        btn.setBorderPainted(false); // Hace el botón plano (opcional)
        btn.setOpaque(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarResumen;
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnBuscarPalabra;
    private javax.swing.JButton btnSeleccionarArchivo;
    private javax.swing.JButton btnVerDetallesAutor;
    private javax.swing.JButton btnVerDetallesPC;
    private javax.swing.JButton btnVerDetallesPCLista;
    private javax.swing.JComboBox<String> cmbAutores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblDetallesPCLista;
    private javax.swing.JLabel lblInstruccionAnalizar;
    private javax.swing.JLabel lblInstruccionAutor;
    private javax.swing.JLabel lblInstruccionListaPC;
    private javax.swing.JLabel lblInstruccionPC;
    private javax.swing.JLabel lblResultadosAnalisis;
    private javax.swing.JLabel lblResultadosPC;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblTituloAgregar;
    private javax.swing.JList<String> lstInvestigaciones;
    private javax.swing.JPanel pnlAgregarResumen;
    private javax.swing.JPanel pnlAnalizarResumen;
    private javax.swing.JPanel pnlBuscarAutor;
    private javax.swing.JPanel pnlBuscarPalabraClave;
    private javax.swing.JPanel pnlListarPalabras;
    private javax.swing.JScrollPane scrDetallesPalabraClave;
    private javax.swing.JScrollPane scrListaInvestigaciones;
    private javax.swing.JScrollPane scrListaPalabrasClave;
    private javax.swing.JScrollPane scrReporteAnalisis;
    private javax.swing.JScrollPane scrResultadosPalabra;
    private javax.swing.JTextArea txtDetallesPalabraClave;
    private javax.swing.JTextField txtPalabraClave;
    // End of variables declaration//GEN-END:variables
}
